### ISSUE TITLE
Build fails due to unescaped bracket error on WSL

### ISSUE THREAD

**Issue by siriuspal** [tommie/lx106-hal#12]
Not sure if this is a problem in error/warning handling in .configuration, automake or make file, but during installation, it exists while writing to PATH if PATH previously added contains folders names with brackets (). This is true for WSL as windows directories contains (x86) and added to PATH

**Comment by siriuspal** [comment]
Okay, looks like my initial assessment was wrong. This issue persists in perl v5.20 as well. This could be because of spaces in Windows path.

Attached build log.
[build.txt](https://github.com/tommie/lx106-hal/files/1050235/build.txt)

**Comment by tommie** [comment]
/bin/bash: -c: line 0: syntax error near unexpected token `('

Looking at pfalcon/esp-open-sdk#267, it seems this is a problem at https://github.com/pfalcon/esp-open-sdk/blob/b069537944fab5d3a260b82a9aaaad5c560dd6bd/Makefile#L168.
